# Generated by Django 6.0.5 on 2026-05-28 12:18

import django.db.models.deletion
import ingestion.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('sap', 'SAP Procurement CSV'), ('utility', 'Utility Portal CSV'), ('travel', 'Concur Travel CSV')], max_length=20)),
                ('original_filename', models.CharField(max_length=500)),
                ('file', models.FileField(blank=True, null=True, upload_to=ingestion.models.batch_upload_path)),
                ('file_sha256', models.CharField(help_text='SHA-256 of raw file bytes for dedup and integrity', max_length=64)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('row_count_total', models.PositiveIntegerField(default=0)),
                ('row_count_parsed', models.PositiveIntegerField(default=0)),
                ('row_count_failed', models.PositiveIntegerField(default=0)),
                ('row_count_suspicious', models.PositiveIntegerField(default=0)),
                ('parse_errors_summary', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.organization')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.PositiveIntegerField(help_text='1-based row number in the source file')),
                ('raw_data', models.JSONField(help_text='Verbatim parsed row as key-value dict')),
                ('parse_status', models.CharField(choices=[('ok', 'Parsed OK'), ('warning', 'Parsed with warnings'), ('error', 'Parse error — not normalized'), ('skipped', 'Skipped (header/empty row)')], default='ok', max_length=20)),
                ('parse_errors', models.JSONField(default=list, help_text='List of {field, message} dicts describing parse issues')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='ingestion.ingestionbatch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='core.organization')),
            ],
            options={
                'ordering': ['batch', 'row_number'],
            },
        ),
        migrations.AddIndex(
            model_name='ingestionbatch',
            index=models.Index(fields=['organization', 'source_type'], name='ingestion_i_organiz_cb728b_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestionbatch',
            index=models.Index(fields=['organization', 'status'], name='ingestion_i_organiz_297491_idx'),
        ),
        migrations.AddIndex(
            model_name='rawrecord',
            index=models.Index(fields=['organization', 'batch'], name='ingestion_r_organiz_5cd6c7_idx'),
        ),
        migrations.AddIndex(
            model_name='rawrecord',
            index=models.Index(fields=['parse_status'], name='ingestion_r_parse_s_f5a0dd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rawrecord',
            unique_together={('batch', 'row_number')},
        ),
    ]
