# Generated by Django 6.0.5 on 2026-05-28 12:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('ingestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_category', models.CharField(help_text="e.g. 'electricity_kwh_us_average', 'diesel_litre', 'flight_km_economy'", max_length=100)),
                ('scope', models.PositiveSmallIntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('kg_co2e_per_unit', models.DecimalField(decimal_places=8, max_digits=14)),
                ('unit', models.CharField(help_text="Denominator unit, e.g. 'kWh', 'litre', 'km'", max_length=32)),
                ('factor_source', models.CharField(choices=[('epa_egrid', 'EPA eGRID'), ('defra', 'UK DEFRA'), ('icao', 'ICAO Aviation'), ('iea', 'IEA'), ('epa_useeio', 'EPA USEEIO'), ('custom', 'Organization Custom')], max_length=20)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(blank=True, help_text='Null = global factor; non-null = org-specific override', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('sap', 'SAP Procurement CSV'), ('utility', 'Utility Portal CSV'), ('travel', 'Concur Travel CSV')], help_text='Denormalized from batch for fast filtering', max_length=20)),
                ('scope', models.PositiveSmallIntegerField(choices=[(1, 'Scope 1 — Direct'), (2, 'Scope 2 — Purchased Energy'), (3, 'Scope 3 — Value Chain')])),
                ('activity_category', models.CharField(help_text="e.g. 'diesel', 'electricity', 'flight_economy', 'hotel_night'", max_length=100)),
                ('activity_date', models.DateField(help_text='Date the activity occurred (not the ingestion date)')),
                ('vendor', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, help_text='Plant code, service address, city-pair, etc.', max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('raw_quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('raw_unit', models.CharField(help_text='Unit as it appeared in source', max_length=32)),
                ('raw_currency', models.CharField(blank=True, help_text='ISO 4217', max_length=3)),
                ('normalized_quantity', models.DecimalField(decimal_places=4, help_text="Quantity in emission factor's denominator unit", max_digits=18)),
                ('normalized_unit', models.CharField(max_length=32)),
                ('quantity_kg_co2e', models.DecimalField(decimal_places=4, help_text='Calculated emission in kg CO2-equivalent', max_digits=18)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('suspicion_reasons', models.JSONField(default=list, help_text="List of reason codes, e.g. ['outlier_3sigma', 'stale_date']")),
                ('review_status', models.CharField(choices=[('pending', 'Pending Review'), ('flagged', 'Flagged / Suspicious'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emission_records', to='ingestion.ingestionbatch')),
                ('emission_factor_used', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applied_records', to='emissions.emissionfactor')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_records', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='core.organization')),
                ('raw_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emission_record', to='ingestion.rawrecord')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-activity_date', 'scope'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Record Created'), ('edited', 'Field Edited'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged as Suspicious'), ('unflagged', 'Suspicion Cleared'), ('locked', 'Locked for Audit'), ('unlocked', 'Unlocked (Admin)'), ('batch_approved', 'Bulk Approved'), ('batch_rejected', 'Bulk Rejected')], max_length=30)),
                ('before_state', models.JSONField(blank=True, null=True)),
                ('after_state', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.organization')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('emission_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='emissions.emissionrecord')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='emissionfactor',
            index=models.Index(fields=['activity_category', 'scope'], name='emissions_e_activit_2e9fcf_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['organization', 'scope', 'review_status'], name='emissions_e_organiz_cbe9aa_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['organization', 'activity_date'], name='emissions_e_organiz_143c84_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['organization', 'source_type'], name='emissions_e_organiz_db4a2d_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['organization', 'is_locked'], name='emissions_e_organiz_1fa8bd_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['is_suspicious', 'review_status'], name='emissions_e_is_susp_633402_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['emission_record', 'timestamp'], name='emissions_a_emissio_9927fe_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['organization', 'timestamp'], name='emissions_a_organiz_dfe771_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['performed_by', 'timestamp'], name='emissions_a_perform_3ac6d9_idx'),
        ),
    ]
